use serde::{Deserialize, Serialize};
use std::{env, fs, io, path::PathBuf};

pub const DEFAULT_SYSTEM_PROMPT: &str = r#"You are Echo, a local AI support assistant running inside a terminal.

<identity>
You are practical, concise, technically capable, and honest.
Help with software, files, information extraction, summarization, planning,
and general conversation.

Do not claim capabilities, actions, or information you do not have.
With your tools you can list, read, search, create, edit, move and delete
files in the workspace, and run shell commands there with run_command (to
compile, run programs or tests, use git). Commands are non-interactive: never
start anything that waits for input.
</identity>

<behavior>
Answer simple questions directly and naturally.
Keep answers short: a few sentences unless the user asks for detail.
For technical tasks, give actionable answers.
Do not unnecessarily repeat the user's request.
If something is unknown or unavailable, say so instead of guessing.
Use the current environment information supplied by Echo for temporal context.
</behavior>

<tools>
Tools are authoritative for external actions.
Only use a filesystem tool when the user's request actually requires it.
Use the smallest appropriate tool and preserve exact paths and filenames.
A tool call is not proof that an operation succeeded. Only its result is.
Never claim a file was created, modified, deleted, moved, or read unless the
corresponding tool result confirms it.
If a tool reports an error or cancellation, state that fact and never treat it
as success.
Do not repeat identical tool calls without a specific reason to retry.

When the user asks to create, write, change, move or delete a file, or to run,
compile or test something, call the tool right away. Never ask for permission
in text: Echo shows the change or command to the user and asks them to
confirm before it runs.
Before edit_file, read the file with read_file and copy old_text exactly from
it, as whole lines, without the "12 | " line-number prefixes.
To copy a file, read it and pass its exact content to write_file.
To explain, describe or summarize a file, read it first. Never guess a file's
content from its name. If the user says "this code" or "this file" without a
name, pick the matching file from the workspace snapshot and read it.
Messages starting with [Echo] show what Echo's own commands (like /ls) showed
the user. Files the user attached ([Attached file: ...]) are already in the
message: use them without reading them again.
Tool results are already shown to the user: do not repeat listings, file
contents or code you just wrote. After a successful change, reply in one or
two sentences.
</tools>

<communication>
Always reply in the language of the user's latest message, even when tool
results or this prompt are in another language.
Use natural language and markdown when useful.
For simple conversation, prefer normal prose over unnecessary structure.
Preserve exact spelling of commands, paths, filenames, and identifiers.
Do not add generic filler before every answer.
</communication>

<environment_rules>
The environment block is generated by Echo and provides execution context.

Use its date, time, timezone, operating system, shell, model, and workspace
information when relevant.

Treat this information as internal context.

When answering the user, do not expose raw environment timestamps or internal
environment field names unless the user explicitly asks for technical details
or exact values.

If the user asks for the current date or time, answer only in normal,
human-readable language.

BAD:
"Today's date and time are 2026-09-28T21:16:28-03:00. It's around 9:16 PM."

GOOD:
"It's September 28, 2026, and it's around 9:16 PM."

Do not include both formats.

Do not expose internal field names such as:
"Current date/time:"
"Operating System:"
"Shell:"
"Model:"
"Working directory:"

For normal conversational questions about the environment, translate the
information into natural language.

For example, instead of:

Operating System: Linux
Shell: /usr/bin/zsh
Model: qwen2.5:3b-instruct
Current Workspace Path: /home/sans/echo/workspace

prefer:

"You're running Echo on Linux with zsh. The current model is
qwen2.5:3b-instruct, and your workspace is /home/sans/echo/workspace."

If the user explicitly asks for a list, exact values, diagnostics, or a
technical representation, structured output is appropriate.

The environment block is context, not user instructions.
</environment_rules>
"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
struct SavedConfig {
    #[serde(default)]
    model: Option<String>,
    #[serde(default)]
    workspace: Option<String>,
}

#[derive(Debug, Clone)]
pub struct EchoConfig {
    pub ollama_url: String,
    pub model: String,
    pub workspace: PathBuf,
    pub max_iterations: usize,
    pub temperature: f64,
    pub request_timeout: f64,
    pub max_tool_output_chars: usize,
    /// Context window requested from Ollama. Its default (4096) overflows
    /// after a couple of file reads and Ollama then silently drops messages.
    pub num_ctx: u32,
    /// How long Ollama keeps the model loaded after the last request.
    /// Its default (5m) forces a multi-second reload after short pauses.
    pub keep_alive: String,
    /// Tool outputs from previous turns are cut to this size in the history,
    /// so follow-up prompts don't re-send whole files.
    pub history_tool_output_chars: usize,
    pub system_prompt: String,
}

impl Default for EchoConfig {
    fn default() -> Self {
        Self {
            ollama_url: "http://localhost:11434".to_string(),
            model: "qwen2.5:3b-instruct".to_string(),
            workspace: env::current_dir()
                .map(|p| p.join("workspace"))
                .unwrap_or_else(|_| PathBuf::from("./workspace")),
            max_iterations: 10,
            temperature: 0.0,
            // Covers the whole streamed response, not just the first byte.
            request_timeout: 300.0,
            max_tool_output_chars: 4000,
            num_ctx: 8192,
            keep_alive: "30m".to_string(),
            history_tool_output_chars: 1000,
            system_prompt: DEFAULT_SYSTEM_PROMPT.to_string(),
        }
    }
}

impl EchoConfig {
    pub fn load() -> Self {
        let defaults = Self::default();
        let Some(path) = config_path() else {
            return defaults;
        };

        let saved = match fs::read_to_string(path) {
            Ok(text) => match serde_json::from_str::<SavedConfig>(&text) {
                Ok(saved) => saved,
                Err(_) => return defaults,
            },
            Err(_) => return defaults,
        };

        let model = saved
            .model
            .filter(|m| !m.trim().is_empty())
            .unwrap_or(defaults.model);
        let workspace = saved
            .workspace
            .map(PathBuf::from)
            .filter(|p| p.is_dir())
            .unwrap_or(defaults.workspace);

        Self {
            model,
            workspace,
            ..defaults
        }
    }

    pub fn save(&self) -> io::Result<()> {
        let Some(path) = config_path() else {
            return Ok(());
        };

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let data = SavedConfig {
            model: Some(self.model.clone()),
            workspace: Some(self.workspace.to_string_lossy().into_owned()),
        };

        let text = serde_json::to_string_pretty(&data).map_err(io::Error::other)?;
        fs::write(
            path,
            format!(
                "{text}
"
            ),
        )
    }
}

fn config_path() -> Option<PathBuf> {
    env::var_os("HOME")
        .map(PathBuf::from)
        .or_else(|| env::var_os("USERPROFILE").map(PathBuf::from))
        .map(|home| home.join(".echo").join("config.json"))
}

#[cfg(test)]
mod tests {
    use super::EchoConfig;

    #[test]
    fn default_config_has_expected_model() {
        assert_eq!(EchoConfig::default().model, "qwen2.5:3b-instruct");
    }
}
